// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, Building, Shield, Star, Users, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Why Us?"
          title="Empowering the AI Workforce"
          description="We are dedicated to building a smarter, more connected AI ecosystem. Join us as we redefine the future of intelligent collaboration."
          items={[
            {
              icon: Zap,
              title: "Fast Processing",
              description: "Quick application reviews.",
            },
            {
              icon: Shield,
              title: "Secured Data",
              description: "Your info is safe.",
            },
            {
              icon: Award,
              title: "Verified Roles",
              description: "Hand-picked opportunities.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/robot-hand-3d-ai-technology_53876-129779.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
