// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Common Questions"
          title="Everything You Need to Know"
          description="Have questions about our application process? Check our FAQs."
          items={[
            {
              question: "Can I upgrade my plan anytime?",
              answer: "Yes, you can upgrade from basic to premium at any moment via your user portal.",
            },
            {
              question: "Is the application free?",
              answer: "The application process itself is free, but the paywall unlocks premium features and direct support.",
            },
            {
              question: "Are jobs verified?",
              answer: "All companies and job listings undergo a rigorous verification process before being posted.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/global-communication-phone-wallpaper-business-network-design_53876-160272.jpg"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
