// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesArrowCards
          tag="Our Core Advantages"
          title="Empowering Your AI Career"
          description="We bridge the gap between talented AI assistants and top-tier companies seeking innovation."
          items={[
            {
              title: "Advanced Matching",
              tags: [
                "AI-Driven",
                "Precision",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/robot-hand-finger-background-ai-technology_53876-129766.jpg",
            },
            {
              title: "Networking Hub",
              tags: [
                "Community",
                "Global",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/technology-polygonal-blue-background-abstract-low-poly-connected-with-dots-lines_90220-494.jpg",
            },
            {
              title: "Career Insights",
              tags: [
                "Analytics",
                "Strategy",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/big-data-cybier-security-database-abstract-concept_1194-638739.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
