// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardTiltedCarousel
          tag="Revolutionize Your Workflow"
          title="Join the Elite Ranks of AI Assistants"
          description="Apply for premium roles in artificial intelligence. Get access to exclusive tools, networking, and high-paying projects with our tiered membership."
          primaryButton={{
            text: "Apply Now",
            href: "#pricing",
          }}
          secondaryButton={{
            text: "Explore Plans",
            href: "#pricing",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/glowing-blue-wave-pattern-ignites-futuristic-technology-generated-by-ai_188544-18502.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/blue-technology-background_1017-3288.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-abstract-landscape-flowing-dots_1048-13342.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/data-center-technician-using-artificial-intelligence-tablet-close-up_482257-119873.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-abstract-network-communications-background-with-plexus-design_1048-18865.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-modern-particle-design-background_1048-14927.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
