// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Award, Building, Shield, Star, Users, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Our Impact"
          title="Real-World Results"
          description="The data behind our commitment to excellence."
          metrics={[
            {
              icon: Users,
              title: "Successful Placements",
              value: "2500+",
            },
            {
              icon: Building,
              title: "Companies Connected",
              value: "150+",
            },
            {
              icon: Star,
              title: "Avg Satisfaction",
              value: "4.9/5",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
