/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Check } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import GridOrCarousel from "@/components/ui/GridOrCarousel";
import ScrollReveal from "@/components/ui/ScrollReveal";

const plans = [
  {
    tag: "Basic",
    price: "$5",
    description: "Perfect for starters.",
    features: [
      "Standard job listing access",
      "Community forum access",
      "Weekly email updates"
    ],
    primaryButton: {
      text: "Get Started",
      href: "#contact"
    }
  },
  {
    tag: "Premium",
    isPopular: true,
    price: "$15",
    description: "For high-performers.",
    features: [
      "Priority job applications",
      "Direct recruiter networking",
      "Exclusive AI tool training",
      "Advanced performance analytics"
    ],
    primaryButton: {
      text: "Go Premium",
      href: "#contact"
    }
  }
];

type PricingPlan = {
  tag: string;
  price: string;
  description: string;
  features: string[];
  primaryButton: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
};

const PricingInline = () => (
  <section aria-label="Pricing section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center w-content-width mx-auto gap-2">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Choose Your Path"}</p>
        </div>

        <TextAnimation
          text={"Flexible Membership Plans"}
          variant={"fade"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Unlock your potential with our basic and premium access tiers."}
          variant={"fade"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="slide-up">
        <GridOrCarousel>
          {plans.map((plan) => (
            <div key={plan.tag} className="flex flex-col items-center gap-4 xl:gap-5 2xl:gap-6 p-6 xl:p-7 2xl:p-8 h-full card rounded text-center">
              <div className="flex items-center gap-2">
                <div className="px-3 py-1 text-sm card rounded w-fit">
                  <p>{plan.tag}</p>
                </div>
                {plan.isPopular && (
                  <div className="px-3 py-1 text-sm bg-primary-cta text-primary-cta-text rounded w-fit font-medium">
                    <p>Most Popular</p>
                  </div>
                )}
              </div>

              <div className="flex flex-col gap-1">
                <span className="text-5xl md:text-6xl font-semibold">{plan.price}</span>
                <span className="text-base font-medium">{plan.description}</span>
              </div>

              <div className="flex flex-col gap-3 w-full">
                <Button text={plan.primaryButton.text} href={plan.primaryButton.href} variant="primary" className="w-full" />
                {plan.secondaryButton && <Button text={plan.secondaryButton.text} href={plan.secondaryButton.href} variant="secondary" className="w-full" />}
              </div>

              <div className="w-full h-px bg-foreground/20" />

              <div className="flex flex-col gap-3 w-full">
                {plan.features.map((feature) => (
                  <div key={feature} className="flex items-start gap-3">
                    <div className="flex items-center justify-center shrink-0 size-6 primary-button rounded">
                      <Check className="size-3 text-primary-cta-text" strokeWidth={2} />
                    </div>
                    <span className="text-base text-left">{feature}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </GridOrCarousel>
      </ScrollReveal>
    </div>
  </section>
);

export default function PricingSection() {
  return (
    <div data-webild-section="pricing" id="pricing">
      <PricingInline />
    </div>
  );
}
