// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Our Community"
          title="Success Stories"
          description="Hear from professionals who have elevated their careers."
          testimonials={[
            {
              name: "Alex R.",
              role: "AI Specialist",
              quote: "The premium tier helped me land my dream role in 2 weeks.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-employee-happy-be-back-work_23-2148727616.jpg",
            },
            {
              name: "Sarah K.",
              role: "Product Lead",
              quote: "Unparalleled networking opportunities in the industry.",
              imageSrc: "http://img.b2bpic.net/free-photo/successful-entrepreneur-working-financial-forecasts-his-desk_482257-123891.jpg",
            },
            {
              name: "Mark D.",
              role: "Data Scientist",
              quote: "The platform interface is intuitive and efficient.",
              imageSrc: "http://img.b2bpic.net/free-photo/elegant-young-businesswoman-posing_329181-11390.jpg",
            },
            {
              name: "Elena V.",
              role: "AI Architect",
              quote: "High quality roles matched perfectly with my skill set.",
              imageSrc: "http://img.b2bpic.net/free-photo/confident-male-student-wears-spectacles-cap-jacket-has-serious-expression_273609-8692.jpg",
            },
            {
              name: "James L.",
              role: "Developer",
              quote: "Well worth the $15 investment.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-portrait-young-handsome-successful-man_1163-5475.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
